/**
 * Generates an array of `n` elements by applying a provided function `f` to each index.
 *
 * @template T - The type of elements in the resulting array.
 * @param {number} n - The number of elements to generate.
 * @param {(i: number) => T} f - A function that takes an index `i` and returns an element of type `T`.
 * @returns {T[]} An array of `n` elements generated by applying `f` to each index.
 */
export const many = <T>(n: number, f: (i: number) => T): T[] => {
  return [...Array(n)].map((_, i) => f(i));
};
