export * from './page/Divider';
export * from './page/Footer';
export * from './page/FooterContacts';
export * from './page/FormContactModal';
export * from './page/Profile';
export * from './page/Projects';
export * from './page/Skills';
export * from './page/Spider';
export * from './page/Modal';