export { Divider } from "./Divider";
export { Footer } from "./Footer";
export { FooterContacts } from "./FooterContacts";
export { FormContactModal } from "./FormContactModal";
export { Profile } from "./Profile";
export { Projects } from "./Projects";
export { Skills } from "./Skills";
export { Spider } from "./Spider";
export { Modal } from "./Modal";
